networks:
  webnet:

services:
  backend:
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 2s
      retries: 5
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - clickhouse
    networks:
      - webnet
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: infra/frontend/Dockerfile
    volumes:
      - ./social_casino_frontend:/app:ro
    expose:
      - "80"
    networks:
      - webnet
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./social_casino_frontend:/srv/frontend:ro
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - webnet
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:24.4
    # HTTP порт наружу — удобно для локальных проверок
    ports:
      - "8123:8123"
    volumes:
      - ch-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=default
    healthcheck:
      # Проверяем доступность через нативный клиент
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - webnet
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
  ch-data:
