networks:
  webnet:

services:
  backend:
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - webnet
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: infra/frontend/Dockerfile
    volumes:
      - ./social_casino_frontend:/app:ro
    expose:
      - "80"
    networks:
      - webnet
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./social_casino_frontend:/srv/frontend:ro
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - webnet
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
